machine_data:
  target: dev

  outputs:

    dev:
      type: bigquery
      method: oauth
      project: project-7792d7ca-4ff6-4f52-91b
      dataset: gold
      location: asia-south1
      threads: 4