name: Deploy DAGs and PySpark app to GCS

on:
  push:
    branches:
      - main

# Required for GitHub OIDC / Workload Identity Federation
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: indigo-medium-506403-t6
      COMPOSER_DAGS_BUCKET: gs://asia-south1-iot-composer-447108cd-bucket
      JARS_BUCKET: gs://socourse_de_1/jars

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/101358511321/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'iot-platform-sa@indigo-medium-506403-t6.iam.gserviceaccount.com'
          token_format: 'access_token'
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Show gcloud version
        run: gcloud version

      - name: Sync DAGs to Composer bucket
        run: |
          echo "Syncing ./src -> $COMPOSER_DAGS_BUCKET"
          gsutil -m rsync -r ./src "$COMPOSER_DAGS_BUCKET"